			<section>
				<h2>Spacing</h2>
				<div>
					<?php $spacers = array(
						'm-0',
						'mx-0',
						'my-0',
						'mt-0',
						'mr-0',
						'mb-0',
						'ml-0',
						'm-15',
						'mx-15',
						'my-15',
						'mt-15',
						'mr-15',
						'mb-15',
						'ml-15',
						// 'm-n15',
						// 'mx-n15',
						// 'my-n15',
						// 'mt-n15',
						// 'mr-n15',
						// 'mb-n15',
						// 'ml-n15',
						'm-auto',
						'mx-auto',
						'my-auto',
						'mt-auto',
						'mr-auto',
						'mb-auto',
						'ml-auto',
						'm-sm-15',
						'mx-sm-15',
						'my-sm-15',
						'mt-sm-15',
						'mr-sm-15',
						'mb-sm-15',
						'ml-sm-15',
						'm-md-15',
						'mx-md-15',
						'my-md-15',
						'mt-md-15',
						'mr-md-15',
						'mb-md-15',
						'ml-md-15',
						'm-lg-15',
						'mx-lg-15',
						'my-lg-15',
						'mt-lg-15',
						'mr-lg-15',
						'mb-lg-15',
						'ml-lg-15',
						'p-0',
						'px-0',
						'py-0',
						'pt-0',
						'pr-0',
						'pb-0',
						'pl-0',
						'p-15',
						'px-15',
						'py-15',
						'pt-15',
						'pr-15',
						'pb-15',
						'pl-15',
						// 'p-n15',
						// 'px-n15',
						// 'py-n15',
						// 'pt-n15',
						// 'pr-n15',
						// 'pb-n15',
						// 'pl-n15',
						'p-sm-15',
						'px-sm-15',
						'py-sm-15',
						'pt-sm-15',
						'pr-sm-15',
						'pb-sm-15',
						'pl-sm-15',
						'p-md-15',
						'px-md-15',
						'py-md-15',
						'pt-md-15',
						'pr-md-15',
						'pb-md-15',
						'pl-md-15',
						'p-lg-15',
						'px-lg-15',
						'py-lg-15',
						'pt-lg-15',
						'pr-lg-15',
						'pb-lg-15',
						'pl-lg-15'
					); ?>
					<?php foreach ($spacers as &$value) : ?>
						<p class="<?php echo $value;?>"><?php echo $value;?></p>
					<?php endforeach;?>
				</div>
			</section>
